services:
  gateway-api:
    build: ./gatewayAPI
    ports:
      - "5000:80"
    depends_on:
      - character_service
    environment:
      - CHARACTER_SERVICE_URL=http://character_service:5001
    networks:
      - dungeon-tax-net
  
  player_service:
    build: ./player_service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    networks:
      - dungeon-tax-net

  character_service:
    build: ./character_service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
    networks:
      - dungeon-tax-net

  tax_service:
    build: ./tax_service
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
    networks:
      - dungeon-tax-net

networks:
  dungeon-tax-net:
    driver: bridge
